### ISSUE TITLE
Rounded polygons cause a crash when they have two outgoing bezier edges

### ISSUE THREAD

**Issue by jl-associo** [cytoscape/cytoscape.js#3282]
**Environment info**

- Cytoscape.js version : 3.30.2
- Browser/Node.js & version : Whatever's setup in JSBin

**Current (buggy) behaviour**

If you have a rounded polygon shape like `round-triangle` or `round-hexagon` that has two outgoing bezier edges to another node then it crashes with the following error log:

`Uncaught TypeError: Cannot read properties of undefined (reading 'corners')
    at Object.getOrCreateCorners (cytoscape.min.js:32:155198)
    at Object.intersectLine (cytoscape.min.js:32:156363)
    at eu.tryToCorrectInvalidPoints (cytoscape.min.js:32:106612)
    at y (cytoscape.min.js:32:112356)
    at eu.findEdgeControlPoints (cytoscape.min.js:32:112572)
    at ru.recalculateEdgeProjections (cytoscape.min.js:32:118159)
    at y.recalculateRenderedStyle (cytoscape.min.js:32:126825)
    at Object.i [as fn] (cytoscape.min.js:32:125998)
    at yu (cytoscape.min.js:32:163189)
    at n (cytoscape.min.js:32:163386)`

Following the code - it looks like it's crashing because it's trying to read `corners` from `rs` which should be the `srcRs` from `_loop`. The issue is when `edgeIsSwapped` is `true` as, unlike the `pairInfo`, the `swappedpairInfo` doesn't have `srcRs` or `tgtRs`.

In the unbuilt code it looks like it's here: https://github.com/cytoscape/cytoscape.js/blob/bce954c2bc34b88c46fe4503af9eb8b824fb6ffd/src/extensions/renderer/base/coord-ele-math/edge-control-points.js#L944

**Desired behaviour**

It shouldn't crash and should display the nodes correctly with the two edges between them.

**Minimum steps to reproduce**

JSBin: https://jsbin.com/sakefatibu/edit?html,js,console,output

Move the nodes around a bit and it will crash.

**Comment by mikekucera** [comment]
Thank you for the excellent bug report and analysis.
